// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYFclhsXWl2FsOBd_tTYGChNiqDvKZO1Q',
    appId: '1:926680717914:web:80ab4f1bf8e55a7c7f5663',
    messagingSenderId: '926680717914',
    projectId: 'travelmate-9b394',
    authDomain: 'travelmate-9b394.firebaseapp.com',
    storageBucket: 'travelmate-9b394.firebasestorage.app',
    measurementId: 'G-PVX0VGNDJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWlFRVuP-ecvobj3xfU5I-9mrK7l6So38',
    appId: '1:926680717914:android:1342cd1c24a9c2667f5663',
    messagingSenderId: '926680717914',
    projectId: 'travelmate-9b394',
    storageBucket: 'travelmate-9b394.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi52Vx7FYB1tt2t3M1gPDD-CO5fft-Tjk',
    appId: '1:926680717914:ios:18734cd6b26655177f5663',
    messagingSenderId: '926680717914',
    projectId: 'travelmate-9b394',
    storageBucket: 'travelmate-9b394.firebasestorage.app',
    iosBundleId: 'com.example.travelMateApp',
  );
}
